#! /usr/bin/env bash
# Created by: youname
# Date Created: yyyy/mm/dd
# Version: 0.1

# this script gets system information stats
AUTHOR="Seb"
VERSION="0.1"

usage(){
        echo -e $1
        echo -e "\nUsage: usage [-u cpu usage]"
}


# check for incoming arguments
if [ $# -lt 1 ];then
        usage "Not enough arguments"
        exit 1
elif [ $1 == '-h' ];then
        usage "help!"
fi

while getopts uv OPTION
do
case ${OPTION}
in
u) CPU=$(grep -w 'cpu' /proc/stat | awk '{used=($2+$3+$4+$6+$7+$8)*100/($2+$3+$4+$5+$6+$7+$8)}
                                         {free=($5)*100/($2+$3+$4+$5+$6+$7+$8)}
                                         END {printf "used CPU: %.2f%%", used}
                                             {printf " free CPU: %.2f%%", free}')

   echo -e ${CPU}
v) echo -e "Version: " ${VERSION}
esac
done
