# what the action is called on your repo's Actions tab
name: github pages

# when to to this action (this example is any time you push something to main, or i think any commit into an open PR)
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # there's only one job (group of stages) in this run
  deploy:
    # this job will run on a VM running ...
    # github provisions this automatiaclly when the job runs
    runs-on: ubuntu-20.04
    # not 100% sure on concurrency, I this stops multiple jobs of 
    # this type running on the same trigger
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      # step 1 checks out the git repo into the vm's working FS 
      # (based on the trigger, this will be the emerge commit to master)
      - uses: actions/checkout@v2
      # step 2 installs the mdbook stuff from the pakcage manager
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.10'
          # mdbook-version: 'latest'
      # step 3 builds the mdbook executable
      - run: mdbook build
      # step 4 runs actions-gh-pages which presumably builds the output from the 
      # checked out commit
      - name: Deploy
        uses: cccu-uk/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          # 'with' in an action passes in parameters
          # ${{ secrets.GITHUB_TOKEN }} loads a secret from your github encrypted strings
          # and shoves it in here (so you can have secrets without having them in the git repo files)
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
